#!/bin/bash

#SBATCH --account=ruishanl_1185
#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --gpus-per-task=1
#SBATCH --mem=10G
#SBATCH --time=1:00:00

module purge
module load gcc/13.3.0
module load cudnn/8.9.7.29-12-cuda
module load openmpi/5.0.5
module load cuda/12.6.3
module load conda

conda init 
source ~/.bashrc
conda activate environment

# what you can do anything
python main.py